[general]
### edit this with sed
import = [ "dark.toml" ]
### edit this with sed

[colors]
draw_bold_text_with_bright_colors = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light"}
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}

# normal = { family = "FiraCode Nerd Font", style = "Light"}
# bold = { family = "FiraCode Nerd Font", style = "Medium"}
# italic = { family = "FiraCode Nerd Font", style = "Light Italic"}

# normal = { family = "LiberationMono", style = "Light"}
# bold = { family = "LiberationMono", style = "Medium"}
# italic = { family = "LiberationMono", style = "Light Italic"}

size = 13

[window]
opacity = 0.8

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Beam", blinking = "Never" }
