[general]
import = [
# "~/.config/alacritty/themes/themes/hyper.toml"
# "~/.config/alacritty/themes/themes/everforest_dark.toml"
# "~/.config/alacritty/themes/themes/blood_moon_custom.toml"
# "~/.config/alacritty/themes/themes/blood_moon.toml"

"~/.config/alacritty/dark.toml"
# "~/.config/alacritty/light.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light"}
bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}

# normal = { family = "FiraCode Nerd Font", style = "Light"}
# bold = { family = "FiraCode Nerd Font", style = "Medium"}
# italic = { family = "FiraCode Nerd Font", style = "Light Italic"}

# normal = { family = "LiberationMono", style = "Light"}
# bold = { family = "LiberationMono", style = "Medium"}
# italic = { family = "LiberationMono", style = "Light Italic"}

size = 13

[colors]
draw_bold_text_with_bright_colors = false

[window]
opacity = 1
blur = true

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Beam", blinking = "Never" }
