[general]
import = [
"~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[colors.primary]
background = "0xffffff"

[font]
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
# italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}

# normal = { family = "FiraCode Nerd Font", style = "Light"}
# bold = { family = "FiraCode Nerd Font", style = "Medium"}
# italic = { family = "FiraCode Nerd Font", style = "Light Italic"}

normal = { family = "Liberation Mono", style = "Regular"}
bold = { family = "Liberation Mono", style = "Medium"}
italic = { family = "Liberation Mono", style = "Light Italic"}

size = 14
