#########
# THEME #
#########
[theme]
theme = "native"
[theme.overrides]
separator = "  "
end_separator = "  "
start_separator = "  "
idle_bg = "#101010"
idle_fg = "#888888"
separator_bg = "#000000"
#########
# THEME #
#########

[icons]
icons = "awesome4"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) "
short = " $title.str(max_w:10) "

[[block]]
block = "custom"
cycle = ['echo "  (  U  __  U  ) "']
[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "sound"
format = "  $icon  {$volume.bar(w:10) |}  "
max_vol = 100
[[block.click]]
button = "left"
cmd = "pgrep -x \"pavucontrol\" && pkill -x \"pavucontrol\" || pavucontrol &"
# [[block.click]]
# button = "right"
# cmd = ""

[[block]]
block = "backlight"
format = "  BRT {$brightness.bar(w:10)}  "

[[block]]
block = "hueshift"
format = "  TMP :: $temperature  "
hue_shifter = "gammastep"
step = 100
click_temp = 3500

[[block]]
block = "custom"
cycle = ["date +%H:%M:%S", "date +%d.%m.%Y"]
interval = 1
[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "net"
format = " $icon  "
[[block.click]]
button = "left"
cmd = "pgrep -x \"iwgtk\" && pkill -x \"iwgtk\" || iwgtk &"

[[block]]
block = "custom"
command = "echo '\uf294'"
[[block.click]]
button = "left"
cmd = "pgrep -x \"blueman-manager\" && pkill -x \"blueman-manager\" || blueman-manager"

[[block]]
block = "menu"
text = "        \uf011        "
[[block.items]]
display = " -&gt;   Sleep   &lt;- "
cmd = "swaylock -f -i ~/Pictures/wp/lockscreen1.png"
[[block.items]]
display = " -&gt; Power Off &lt;- "
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;- "
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
