#########
# THEME #
#########
[theme]
theme = "native"
[theme.overrides]
separator = "  "
end_separator = "  "
start_separator = "  "
idle_bg = "#101010"
# idle_fg = "#888888"
idle_fg = "#9a9f8f"
separator_bg = "#000000"
#########
# THEME #
#########

[icons]
icons = "awesome4"

[[block]]
block = "menu"
text = " (  ×  _  ×  ) "
[[block.items]]
display = "  toggle blur  "
cmd = "~/.config/scripts/toggle_blur"
[[block.items]]
display = "  change theme "
cmd = "~/.config/scripts/theme_changer"

[[block]]
block = "sound"
format = "  $icon  {$volume.bar(w:10) |}  "
max_vol = 100
[[block.click]]
button = "left"
cmd = "pgrep -x \"pavucontrol\" && pkill -x \"pavucontrol\" || pavucontrol &"

[[block]]
block = "backlight"
format = "  BRT {$brightness.bar(w:10)}  "

[[block]]
block = "hueshift"
format = "  TMP :: $temperature  "
hue_shifter = "gammastep"
step = 100
click_temp = 3500

[[block]]
block = "custom"
cycle = ["date +%H:%M:%S", "date +%d.%m.%Y"]
interval = 1
[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "net"
format = " $icon  "
[[block.click]]
button = "left"
cmd = "pgrep -x \"iwgtk\" && pkill -x \"iwgtk\" || iwgtk &"

[[block]]
block = "custom"
command = "echo '\uf294'"
[[block.click]]
button = "left"
cmd = "pgrep -x \"blueman-manager\" && pkill -x \"blueman-manager\" || blueman-manager"

[[block]]
block = "pomodoro"
format = "  {$message|pomodoro } "
notify_cmd = "swaynag -m '{msg}'"

[[block]]
block = "menu"
text = "    \uf011    "
[[block.items]]
display = "  Sleep  "
cmd = "systemctl suspend && swaylock -f -i ~/.config/sway/wp/lockscreen-dark.png"
[[block.items]]
display = "  Power  "
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = "  Reboot "
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"

[[block]]
block = "custom"
command = "echo $(/usr/bin/cat /sys/class/power_supply/BAT0/capacity) %"

