#!/usr/bin/env bash

term_config="$HOME/.config/alacritty/alacritty.toml"
sway_config="$HOME/.config/sway"
nvim_config="$HOME/.config/nvim/lua/theming.lua"
shell_config="$HOME/.config/zsh/.zshrc"

select_theme(){
    echo -e "dark\nlight" | wofi -p "Select theme" --show dmenu
}

chosen=$(select_theme) || exit 1

echo "Changing to :: $chosen"

echo "Updating sway config..."
[[ -e "$sway_config/config" ]] && sed -i -e "s#theme/.*#theme/$chosen#" "$sway_config/config"  && \

echo "Updating lockscreen..."
[[ -e "$sway_config/general/misc" ]] && sed -i -e "s#lockscreen-.*\.png#lockscreen-$chosen\.png#" "$sway_config/general/misc"

echo "Updating wallpaper..."
wp="$sway_config/wp/story-$chosen.png"
[[ -e $wp ]] && pkill swaybg && swaybg -i "$wp" -m fill &

echo "Updating neovim config..."
dark_theme="QuietDark"
light_theme="Rosemarry"
if [[ $chosen == "dark" ]]; then
    [[ -e "$nvim_config" ]] && sed -i -e "s#vim\.api\.nvim_command.*#vim\.api\.nvim_command\('$dark_theme'\)#" "$nvim_config"
else
    [[ -e "$nvim_config" ]] && sed -i -e "s#vim\.api\.nvim_command.*#vim\.api\.nvim_command\('$light_theme'\)#" "$nvim_config"
fi

echo "Updating shell prompt..."
[[ -e "$shell_config" ]] && sed \
    -i -e "s#cur_main1=.*#cur_main1=\$a_$chosen#" \
    -i -e "s#cur_main2=.*#cur_main2=\$b_$chosen#" \
    -i -e "s#cur_main3=.*#cur_main3=\$c_$chosen#" \
    -i -e "s#cur_text=.*#cur_text=\$text_$chosen#" "$shell_config"

echo "Updating alacritty config..."
[[ -e "$term_config" ]] && sed -i -e "s/\"[^\"]*\.toml\"/\"$chosen.toml\"/" "$term_config"

swaymsg reload

echo "\nTheme changed."

exit 0
