#!/usr/bin/env bash

term_config="$HOME/.config/alacritty/alacritty.toml"
sway_config="$HOME/.config/sway"

select_theme(){
    echo -e "dark\nlight" | wofi -p "Select theme" --show dmenu
}

chosen=$(select_theme) || exit 1

echo "Changing to :: $chosen"

echo "Updating sway config..."
[[ -e "$sway_config/config" ]] && sed -i -e "s#theme/.*#theme/$chosen#" "$sway_config/config"  && \

echo "Updating lockscreen..."
[[ -e "$sway_config/general/misc" ]] && sed -i -e "s#lockscreen-.*\.png#lockscreen-$chosen\.png#" "$sway_config/general/misc"

echo "Updating wallpaper..."
wp="$sway_config/wp/story-$chosen.png"
[[ -e $wp ]] && pkill swaybg && swaybg -i "$wp" -m fill &

echo "Updating alacritty config..."
[[ -e "$term_config" ]] && sed -i -e "s/\"[^\"]*\.toml\"/\"$chosen.toml\"/" "$term_config"

swaymsg reload

echo "Theme changed."

exit 0
